site_name: 玉子的笔记本

repo_url: https://github.com/huaxv-code/huaxv-note/
repo_name: 花续情愫缘 / huaxv-note

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true 
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.superfences

theme:
  logo: 'img/头像.png'
  favicon: 'img/头像.png'
  icon:  
    repo: fontawesome/brands/git
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  name: material
  features:
    - navigation.instant
    # - navigation.tracking
    - navigation.tabs 
    # - navigation.tabs.sticky
    # - navigation.sections
    # - toc.integrate # 屏蔽右侧导航栏，合并到左边
    # - navigation.expand
    # - navigation.prune
    # - navigation.prune 
    # - toc.follow
    - navigation.top
    # - toc.integrate
    # - content.code.annotate
    # - content.tabs.link
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: white

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      # accent: deep orange
    # - accent: green

  font:
    code: Roboto Mono
  language: zh

plugins:
  - glightbox
  - search:
      # lang:
      #   - en
      #   - ja
      # separator: '[\s\-\.]+'
      separator: '[\s\u200b\-]'
  #   separator: '[\s\u200b\-]'
  # - with-pdf
    # verbose: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 简介:
    - index.md
    - git.md
  - 算法学习:
    - 高精度:
      - 高精度非负整数:
        - label/算法学习/高精度/高精度非负整数/高精度非负整数.md
    - 数据结构:
      - 单链表:
        - 单链表: label/算法学习/数据结构/单链表/单链表.md
      - 栈: 
        - label/算法学习/数据结构/栈/栈.md
        - label/算法学习/数据结构/栈/后缀表达式.md
        - label/算法学习/数据结构/栈/单调栈.md
      - 队列: 
        - label/算法学习/数据结构/队列/队列.md
        - label/算法学习/数据结构/队列/双端队列.md
        - label/算法学习/数据结构/队列/单调队列.md
        - label/算法学习/数据结构/队列/例题-机器翻译.md
        - label/算法学习/数据结构/队列/例题-滑动窗口.md
      - 堆:
        - 二叉堆: label/算法学习/数据结构/堆/二叉堆.md
        - 配对堆 (可并堆): label/算法学习/数据结构/堆/配对堆.md
        - 左偏树 (可并堆): label/算法学习/数据结构/堆/左偏树.md
      - 并查集: 
        - label/算法学习/数据结构/并查集/并查集.md
      - 分块思想: 
        - label/算法学习/数据结构/分块思想/分块思想.md
      - ST 表: 
        - label/算法学习/数据结构/ST 表/ST 表.md
      - 树状数组: 
        - label/算法学习/数据结构/树状数组/树状数组.md
      - 哈夫曼树: 
        - label/算法学习/数据结构/哈夫曼树/霍夫曼树.md
      - 字符串哈希: 
        - label/算法学习/数据结构/字符串哈希/字符串哈希.md
      - 二叉树: 
        - label/算法学习/数据结构/二叉树/二叉树.md
      - 线段树: 
        - label/算法学习/数据结构/线段树/线段树.md
    - 排序:
      - 快速排序: label/算法学习/排序/快速排序.md
      - 归并排序: label/算法学习/排序/归并排序.md
    - 查找:
      - 二分查找: label/算法学习/查找/二分查找.md
      - label/算法学习/查找/猜分数.md
    - 数论:
      - lowbit: label/算法学习/数论/lowbit.md
      - 二进制 1 的个数: label/算法学习/数论/二进制 1 的个数.md
      - 试除法判质数: label/算法学习/数论/试除法判质数.md
      - 暴力分解质因子: label/算法学习/数论/暴力分解质因子.md
      - 欧拉筛质数: label/算法学习/数论/欧拉筛质数.md
      - 介绍大数 __int128_t: label/算法学习/数论/int128.md
      - 快速幂: label/算法学习/数论/快速幂.md
      # - 素性探测: label/算法学习/数论/素性探测.md
      - 素性探测判质数: label/算法学习/数论/素性探测判质数.md
      - 最大公约数 gcd: label/算法学习/数论/最大公约数 gcd.md
      - 最小公倍数 lcm: label/算法学习/数论/最小公倍数 lcm.md
      - 扩展欧几里得算法: label/算法学习/数论/扩展欧几里得算法.md
      - 试除法求约数: label/算法学习/数论/试除法求约数.md
      - 约数和定理: label/算法学习/数论/约数和定理.md
      - 欧拉函数: label/算法学习/数论/欧拉函数.md
    - 图论:
      - dijkstra 算法正权路径求最短路: label/算法学习/图论/dijkstra算法正权路径求最短路.md
    - 字符串:
      - kmp: label/算法学习/字符串/kmp.md
  # - 高等数学:
  #   - 二重积分: label/高等数学/二重积分.md
  - 概率统计:
    - 读我: label/概率统计/读我.md
    - 赌局中断: label/概率统计/赌局中断.md
    - label/概率统计/约定相遇.md
    - label/概率统计/n中取r.md
    - label/概率统计/分鞋子.md
    - label/概率统计/公平的棋局.md
    - label/概率统计/家庭的小孩全是同性.md
    - label/概率统计/机器检验阳性.md
    - label/概率统计/赌博规则.md
    - label/概率统计/两粒骰子.md
    - label/概率统计/二项分布.md
    - label/概率统计/泊松分布.md
    - label/概率统计/二项分布可近似看成泊松分布的情况.md
    - label/概率统计/分布函数与概率密度函数.md
    - label/概率统计/正太分布.md
    - label/概率统计/指数分布.md
    - label/概率统计/均匀分布.md
    - label/概率统计/多维离散型随机向量.md
    - label/概率统计/多项式分布.md
    - label/概率统计/取出次品的个数.md
    - label/概率统计/五重伯努利试验.md
    - 概率密度函数简单例题: label/概率统计/概率密度函数.md
    - 均匀分布简单例题: label/概率统计/均匀分布简单例题.md
    - 指数分布简单-例题: label/概率统计/指数分布简单例题.md
    - 正太分布简单例题: label/概率统计/正太分布简单例题.md
    - 分布函数简单例题: label/概率统计/分布函数简单例题.md
    - 概率密度函数简单例题: label/概率统计/概率密度函数简单例题.md
    - 二维随机向量简单例题引入: label/概率统计/二维随机向量简单例题.md
    - 二维均匀分布简单例题: label/概率统计/二维均匀分布简单例题.md
    - 二维正太分布简单例题: label/概率统计/二维正太分布简单例题.md
    - 边缘分布简单例题: label/概率统计/二维连续型随机变量的边缘分布简单例题.md

  - 刷题册:
    - 剩下的数: label/刷题册/剩下的数.md
    - D-莲子的物理热力学: label/刷题册/D-莲子的物理热力学.md
    - 盛最多水的容器: label/刷题册/盛最多水的容器.md
    - 消耗体力爬得更高: label/刷题册/消耗体力爬得更高.md
    - 最大子段和: label/刷题册/最大子段和.md
    - 验证栈序列: label/刷题册/验证栈序列.md
    - 约瑟夫问题: label/刷题册/约瑟夫问题.md
    - 孤独的照片: label/刷题册/孤独的照片.md
    - 判断连通: label/刷题册/判断连通.md